baptisteArno/typebot.io

packages/bot-engine/src/services/logic.ts

fix(engine): 🐛 Current id bug when linking to current bot

---

apps/builder/package.json
packages/bot-engine/package.json

Fix docker prod 'qs' missing

---

apps/builder/components/theme/GeneralSettings/FontSelector/FontSelector.tsx

fix: 🐛 Remove missing creds GFont error

---

apps/viewer/pages/[[...publicId]].tsx

fix(viewer): 🐛 Ignoring port number when checking matching URL

---

apps/viewer/pages/[[...publicId]].tsx

fix(viewer): 🐛 Forwarded host checking

---

apps/viewer/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.ts
packages/bot-engine/src/services/variable.ts

fix(engine): 🐛 Multi-line var parsing for webhook

---

docker-compose.yml

Builder: remove build step and update db reference

Update compose file

---

apps/builder/pages/api/auth/adapter.ts
apps/docs/docs/self-hosting/configuration.mdx

feat(auth): 🛂 Disable new user signups

---

packages/bot-engine/src/services/logic.ts

fix(engine): 🐛 Variable value reset

---

apps/docs/docs/self-hosting/docker.mdx

fix(docs): ✏️ Docker upgrade instructions

---

apps/docs/docs/self-hosting/configuration.mdx

fix: ✏️ Remove quotes from email config

---

apps/builder/playwright/fixtures/typebots/inputs/variableButton.json
apps/builder/playwright/tests/inputs/buttons.spec.ts
packages/bot-engine/src/components/ChatGroup/ChatBlock/InputChatBlock.tsx
packages/bot-engine/src/components/ChatGroup/ChatBlock/inputs/ChoiceForm.tsx
packages/bot-engine/src/components/ChatGroup/ChatGroup.tsx

feat(bot): ✨ Support variables in buttons

---

.github/workflows/playwright.yml
apps/builder/components/results/SubmissionsTable/SubmissionsTable.tsx
apps/builder/layouts/results/SubmissionContent.tsx
apps/builder/mocks/index.ts
apps/builder/services/typebots/results.tsx
apps/viewer/playwright/tests/fileUpload.spec.ts

fix: 🐛 Display file URL in CSV export

---

apps/builder/playwright/tests/settings.spec.ts
apps/builder/playwright/tests/templates.spec.ts
apps/viewer/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.ts
packages/bot-engine/src/services/variable.ts

fix(webhook): 🐛 Properly escape backslash and quotes

---

apps/docs/docs/self-hosting/configuration/_category_.json
apps/docs/docs/self-hosting/configuration/builder.mdx
apps/docs/docs/self-hosting/configuration/overview.md
apps/docs/docs/self-hosting/configuration/viewer.mdx
apps/docs/docs/self-hosting/docker.mdx
docker-compose.dev.yml
docker-compose.yml

docs: 📝 Improve docker guides and examples

---

Dockerfile

PR reduces the docker image size—a summary of the changes
* Added `--no-install-recommends` to `apt` and `autoremove`+`clean` as per [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run) 
* Merged the last two `RUN` directives into one to reduce layers 
* Merged the two entrypoint `COPY` directives into one. 
* Added `SHELL` directive `["/bin/bash", "-o", "pipefail", "-c"]` in the builder since the `RUN` command uses a pipe
* Added various quotes for variables to avoid potential word splitting
Followed rules from [hadolint](https://github.com/hadolint/hadolint), [shellcheck](https://github.com/koalaman/shellcheck) and [dive](https://github.com/wagoodman/dive)
Since it's a multi-stage build since I didn't reduce layers in the builder images since …

improve Dockerfile size and safety

---

apps/builder/src/features/blocks/inputs/phone/components/PhoneNumberSettingsBody/CountryCodeSelect.tsx

added Tanzania (+255) to the country code list

added Tanzania to the country code list

---

apps/builder/src/features/settings/components/MetadataForm.tsx
apps/builder/src/features/settings/settings.spec.ts
apps/docs/docs/editor/settings.mdx
apps/viewer/src/components/Seo.tsx
apps/viewer/src/components/TypebotPage.tsx
apps/viewer/src/features/settings/settings.spec.ts
apps/viewer/src/lib/google-tag-manager.ts
packages/models/src/features/typebot/settings.ts

This pull request adds Google Tag Manager to the application. With Tag Manager, you can manage and control tracking tags on your website without having to modify the source code. This allows you to measure the performance of your website and collect data to improve performance and user experience. In addition, Tag Manager allows you to easily implement new tags and integrations with other marketing and analytics tools without having to redeploy the application code.

feat: add Google Tag Manager

---

README.md

Fixes a small typo in the README.

🐛 Fix readme typo

---

scripts/inject-runtime-env.sh

Fix typo in inject-runtime-env.sh

---

Dockerfile

Changed Dockerfile image due to node-18 compatibility issues with Docker `version 20.10.7, build f0df350`
Ref
https://github.com/nodejs/node/issues/43064

Changed the Dockerfile image

---

.github/workflows/publish_docker_images.yml

:green_heart: Fix docker multi arch overwrite issue

---

apps/docs/self-hosting/troubleshoot.mdx

Hi Arno,
Thank you for your amazing project.
I have made the following small change in the docs:
- "signed" text should be "sign", fixed this small oversight in the docs.

Fix typo in troubleshooting

---

apps/builder/src/features/auth/components/SignInForm.tsx
packages/bot-engine/blocks/inputs/email/formatEmail.ts
packages/bot-engine/continueBotFlow.ts

formats email input to lower case

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

feat: added issue and feature template

---

apps/builder/src/features/editor/components/BlocksSideBar.tsx

Hi, @baptisteArno Added the search input in blocks sidebar.
Resolve #359.
Works with tags and description as well.

Added search input in blocks sidebar #359 

---

apps/docs/editor/blocks/integrations/webhook.mdx

Added section for a simple free tool for debugging webhooks easily. Hope thats ok!

Update webhook.mdx for debugger tool

---

apps/builder/src/features/forge/components/credentials/UpdateForgedCredentialsModalContent.tsx

Fixes #1856 
https://github.com/user-attachments/assets/ae252269-ce9f-4981-8eca-e073adea4455

🐛 Fix issue in credentials modal to properly update value

---

packages/bot-engine/src/continueBotFlow.ts
packages/variables/src/codeRunners.ts
packages/variables/src/executeFunction.ts
packages/variables/src/getOrCreateIsolate.ts
packages/variables/src/parseVariables.ts
packages/variables/src/store.ts

Store existing isolated in global and reuse it

---

apps/docs/mint.json
apps/docs/self-hosting/deploy/alibaba-cloud.mdx
apps/docs/self-hosting/get-started.mdx

📝 docs(self hosting): Add deployment link for Alibaba Cloud

📝 docs(self hosting): Add deployment link for Alibaba Cloud

---

apps/docs/contribute/guides/create-block.mdx

Edited "specficiation" to "specification" and 2 other quick typos for improvement

Fixed typos in create-block.mdx
